### ISSUE TITLE
Store word list files inside vault

### ISSUE THREAD

**Issue by Rubecks** [tth05/obsidian-completr#1]
Firstly, I really like your plugin. Found about it on obsidianroundup.org, and it's the best implementation of the concept that I found for Obsidian.

But, in my opinion, there's a problem with the current implementation of word list files; it uses absolute paths, even if you store the file inside the vault. It's an issue if you use Obsidian in more than one device, having to maintain a copy of the lists and adding different paths to the same file for each device.

A solution is to create a markdown file with all the words inside it, so the file scanner can add them by itself. But then suggestions with multiple words doesn't work the same, since it picks word by word. Not ideal.

Would it be possible to import the word lists to the vault and use relative paths to make the plugin completely portable? Maybe somewhere on the `.obsidian` folder like the css snippets, or even on a note folder like the templates' plugin, but that the scanner ignores.

**Comment by tth05** [comment]
Thanks a lot for the feedback, I'm glad that you like the plugin!
I've changed it so the word lists will now be imported into `.obsidian/plugins/obsidian-completr/wordLists`.
