### ISSUE TITLE
[Feature request] Hide "Loaded X words from Y" message at each startup

### ISSUE THREAD

**Issue by Elaws** [tth05/obsidian-completr#12]
Message "Loaded X words from Y" shows at each startup. Is there any way to hide or disable it ?

Thanks !

**Comment by tth05** [comment]
I don't see how the message is a problem? It shows for 2 seconds, is in the top right corner and Obsidian is not a program that you constantly restart

**Comment by Elaws** [comment]
Thanks for your reply ! 

I don't really see the need for this message at each startup (while it seems perfectly fine when it loads the file for the first time).

I have 40+ plugins installed in Obsidian, and I think it's a better practice if each plugin catches user attention only if needed or important. In an ecosystem shared by many plugins, in can quickly get noisy.

**Comment by tth05** [comment]
Your reasoning does make sense and the message isn't really that useful. Fixed in 476b52cc9cc854a3cd323d42082d6846faae7ef6

**Comment by Elaws** [comment]
Thank you for taking this remark into account !
