### ISSUE TITLE
What is the difference between this plugin and other autocomplete plugins?

### ISSUE THREAD

**Issue by ooker777** [tth05/obsidian-completr#14]
If you don't mind, can I ask what is the different between this plugin and other autocomplete plugins like [Autocomplete](https://github.com/Yeboster/autocomplete-obsidian), [Various Complements](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin)? This is a part of [comparing similar plugins](https://forum.obsidian.md/t/comparisons-of-similar-plugins/32789?u=ooker)

**Comment by ooker777** [comment]
so I take that LaTeX was the primary reason you wanted to make this plugin, right?

**Comment by tth05** [comment]
Yep. But it has evolved into more than that by now.
