### ISSUE TITLE
The slash command does not work with the plugin enabled

### ISSUE THREAD

**Issue by Robertgreene123** [tth05/obsidian-completr#17]
Hey, this is an excellent plugin and i appreciate your efforts; however, it clashes with the slash command plugin, please help.

**Comment by tth05** [comment]
Should be fixed in the next update.

**Comment by Robertgreene123** [comment]
Thanks very much.

**Comment by Robertgreene123** [comment]
Hey, when will the next update be? i am sorry i am impatient but i really enjoy using both plugins and currently it is still impossible.

**Comment by Robertgreene123** [comment]
That is great, thanks a lot.
