### ISSUE TITLE
Optional Modifier for scrolling through suggestions

### ISSUE THREAD

**Issue by Glint-Eye** [tth05/obsidian-completr#20]
Hey me again :P

I recognized that I quite often get into the situation that I want to edit Items of an unordered list for which I often move the cursor up and down between items. Whenever i'm getting a suggestion pop-up I am then accidentally browsing through suggestions instead of moving to another list item.

It would be great if there was an option to need a modifier key (e.g. Ctrl) to browse the suggestions, whereas "up" and "down" by itself just jump the line up and down when the suggestions pop up is open.

Cheers. :)

**Comment by tth05** [comment]
With a lot of pain and suffering I've managed to get hotkey customization working. You should be able to change them to `Ctrl + Up` etc. now. cfc03b18908e8a5737caf9beeb6efae29a3a9b60

**Comment by Glint-Eye** [comment]
works like a charm :)

thx a lot!
