### ISSUE TITLE
Bug about hotkeys

### ISSUE THREAD

**Issue by zcysxy** [tth05/obsidian-completr#21]
The plugin seems to interfere with hotkeys. I'm on macOS, Obsidian v0.14.7. With the plugin turned on, some hotkeys like `cmd + D` and `cmd + L` don't work anymore (regardless of what commands they are binding to). I don't know if this is a bug of the plugin or Obsidian itself.

**Comment by tth05** [comment]
I'm only on v0.14.6 and don't have a mac to test this with. Unless they've changed something internally, my code should replicate the original hotkey behavior. 
1. Did this happen with v0.14.6 as well?
2. Are you using the newest Completr version?
3. Did you maybe have keybind collisions with those keys anywhere?

**Comment by zcysxy** [comment]
Yes, it happens with v0.14.6 and newest Completr, and there are no keybind collisions. Here is the log when I hit the keybind.

```
VM262:2144 Uncaught TypeError: Cannot read properties of undefined (reading 'isVisible')
    at Object.eval [as func] (eval at <anonymous> (app.js:1:1494667), <anonymous>:2144:23)
    at e.handleKey (app.js:1:921501)
    at t.e.handleKey (app.js:1:921614)
    at t.handleKey (app.js:1:921823)
    at e.onKeyEvent (app.js:1:922678)
eval @ VM262:2144
e.handleKey @ app.js:1
e.handleKey @ app.js:1
t.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

**Comment by tth05** [comment]
Ah, I didn't know there was an error. I've published a new version which fixes the error and hopefully your issue as well.
