### ISSUE TITLE
[Bug] `Insert selected suggestion` doesn't work on sidepanes

### ISSUE THREAD

**Issue by firinael** [tth05/obsidian-completr#24]
Pretty self-explanatory. I've got both `Tab` and `Esc` assigned to `Insert selected suggestion`, and neither of them works for auto-completions in sidebar panes. 

And yes, they do work perfectly on main panes, in the same instance, no changes in-between.

EDIT: clicking on the suggestion does work, so it's a thing with the hotkey.

**Comment by tth05** [comment]
Obsidian issue. They've been unable to change 3 lines of code for some reason.
https://forum.obsidian.md/t/hotkeys-commands-should-apply-to-sidebar-notes-when-they-are-focused/2740/23
https://forum.obsidian.md/t/workspace-getactiveviewoftype-does-not-return-markdownview-docked-in-sidebar/37743

**Comment by tth05** [comment]
Fixed in Obsidian `0.15.0` https://forum.obsidian.md/t/obsidian-release-v0-15-0-insider-build/38948
