### ISSUE TITLE
Some comments on Latex mode

### ISSUE THREAD

**Issue by ndharari** [tth05/obsidian-completr#25]
So i found this great plugin (really great!) And i wanted to give u some thoughts. 
As [#11](https://github.com/tth05/obsidian-completr/issues/11) I am using Extended Matjax. For that I'm using some macros that are of lenght 1, like "\f{#}{#}" instead of \frac{#}{#}. For that I assigned the minimum trigger lenght to 1. The problem is that now it appears When i dont write the "\\" sign so:

1.  It would be cool if the latex completion only started after a "\\".

As I added my macros directly to your source code I saw that you have included _all_ mathjax commands... and maybe thats too much (considering I also added my macros!). So:

2. It would be cool if there were so filtering in the latex commands. Not all are really needed. Also, if you end up adding a better way to add macros for completion, then **those commands** should appear first.

Thanks again for the great work!

**Comment by ndharari** [comment]
As in [23](https://github.com/tth05/obsidian-completr/issues/23) we could also blacklist latex environments!

**Comment by tth05** [comment]
> It would be cool if the latex completion only started after a "".

Would do you mean by this? Do you mean `$$`? If the completion triggers outside of latex blocks then that'd be a bug or there is a formatting error in your document.

> It would be cool if there were so filtering in the latex commands. Not all are really needed. Also, if you end up adding a better way to add macros for completion, then those commands should appear first.

This would basically be possible with #11

**Comment by ndharari** [comment]
Really sorry, I don't know why the backlash didn't show. I ment "\".

Great man! Just saw the change. Amazing plugin

**Comment by tth05** [comment]
Ah ok I see. LaTeX suggestions always trigger without a backslash because it's way faster to type that way. Can you explain a bit more why that's a problem in your case?

**Comment by ndharari** [comment]
Ah ok, I see. Maybe I have to tinker a little more with the plugin. For me it was the case that I have lots of  macros that are one letters. If I turn the minimmum trigger lenght to 1 I get it gets obtrusive as in all words I get a prompt. 
But maybe I should test writing without the backslash as you say
