### ISSUE TITLE
option to ignore diacritics on filtering words

### ISSUE THREAD

**Issue by justl00kingfor** [tth05/obsidian-completr#26]
Hi,

Please consider to add an option to ignore diacritics when filtering matches on popup.

Thanks.

**Comment by tth05** [comment]
Can you give an example, please?

**Comment by justl00kingfor** [comment]
For example when I want to match word "ação" in pop up I would like to just type "aca" instead of "açã". 

This will help with languages which use especial characters like ç ć à â ã é ê …

**Comment by tth05** [comment]
Implemented in a185f47cfae79ec074cc102528ece06a7d9e87c0, Completr 2.9.0
