### ISSUE TITLE
Plugin stopped working and changed shift-tab to tab

### ISSUE THREAD

**Issue by pickleton89** [tth05/obsidian-completr#3]
I noticed that my outdent stopped working. It is now the same as shift. Turning of this plugin fixed it. Also, the core functionality of the app is down also. Reload obsidian and reloaded the plugin but all not working. Didn't see anything in the console, unfortunately.

**Comment by tth05** [comment]
For version `2.0.0` you need Obsidian `0.13.14` or higher. I noticed outdent not working as well, didn't know it was my fault. Everything else works fine in `0.13.14`
