### ISSUE TITLE
Ignore Case Not Working for Frontmatter

### ISSUE THREAD

**Issue by savvyslog** [tth05/obsidian-completr#30]
No matter which Word Insertion Mode I select, I can't get the auto-complete to ignore case (like getting "ob" to prompt for the tag "Obsidian")

Just wondering if a recent Obsidian update perhaps broke this, or if I'm missing something.

**Comment by tth05** [comment]
I added a new option for this and updated the description of the other option.
899840bef96c553c3eb6c177bebb0de40eae8bea
