### ISSUE TITLE
Unable to Use Arrows to Select Next/Prev Suggestion in Frontmatter

### ISSUE THREAD

**Issue by savvyslog** [tth05/obsidian-completr#31]
The default (and expected) use of Up or Down keys to move up or down in selection list (for frontmatter, specifically tags) doesn't work. It instead moves the cursor up or down. Perhaps a newer core update is getting in the way?

I was however able to set another keyboard shortcut to work in settings as a workaround for now.

**Comment by tth05** [comment]
Does this always happen or only when you hold arrow up/down?

**Comment by savvyslog** [comment]
It happens every time on single up/down key press, not only if held down.

**Comment by tth05** [comment]
It works perfectly fine in my test setup. I only noticed that the next/previous commands are not repeatable and therefore you can't hold the button.
What obsidian and completr version are you using? Maybe it's some other plugin that is interfering?

**Comment by savvyslog** [comment]
Obsidian version: 0.16.2 (installer version 0.15.9)
Completr version: 2.9.2
System OS: macOS 12.5.1

I tested by disabling all other plugins, but it still occurs. I also installed only this plugin (with no changes to settings) on a fresh new vault and it still happens there, too. (Instead of moving down a selection in the dropdown menu, it moves the cursor down a line on the page)

**Comment by tth05** [comment]
Could be something with the new version, but I don't have access to insider builds, so you're going to have to wait a bit sadly.

**Comment by savvyslog** [comment]
Gotcha, no worries. I look forward to the update when you can get to it.

**Comment by ndharari** [comment]
I have the same problem in obsidian 1.0

**Comment by tth05** [comment]
Seems to have been an easy fix now that I could test it. 98f64d6f71ad527c59d7abcaa3153aadd29debb8
