### ISSUE TITLE
Feature request: An option to disable adding a newline between \begin blocks in latex

### ISSUE THREAD

**Issue by 0xGodspeed** [tth05/obsidian-completr#33]
Current behaviour: after autocompleteing a latex block, the plugin automatically adds a newline between the begin and end blocks.
This is very convenient if you are writing multiline latex ($$ $$)  but not if you are writing it inline ($ $).
It would be really nice if the plugin only adds a newline in multiline mode.
I encountered this problem while trying to write inline 2x2 matrices using $\begin{bmatrix} \end{bmatrix}$.

**Comment by tth05** [comment]
Good catch! I adjusted the behavior fa128768b75f199a39db82e70cd71d93c0a1be75
