### ISSUE TITLE
Can't style selected tag suggestion in popup window

### ISSUE THREAD

**Issue by evanharmon1** [tth05/obsidian-completr#34]
I can't seem to figure out how to change the style of the selected tag suggestion in popup window. I was able to style the suggested tags via

```
completr-suggestion-placeholder {
	color: var(--dark-orange) !important;
}
```

but that styled every tag suggestion _except_ for the highlighted suggestion which is not very visible for me with my current settings:
[screenshot](https://user-images.githubusercontent.com/37220977/197407378-31c50eaf-02e2-4e61-928c-917cb5bf21f4.png)

**Comment by tth05** [comment]
It should be stylable if you select against these classes.
![image](https://user-images.githubusercontent.com/36999320/197600882-ebaabe84-50ae-4259-b829-21b02da6aeba.png)

Example:
```css
.suggestion-item.is-selected {
	background: blue;
}
```
![image](https://user-images.githubusercontent.com/36999320/197601193-474f012f-5e85-490b-9a04-48cf15bd7573.png)

**Comment by tth05** [comment]
@evanharmon1 Does my answer resolved your issue?
