### ISSUE TITLE
[FR] either prioritize words in current file or allow current-only file provider

### ISSUE THREAD

**Issue by huyz** [tth05/obsidian-completr#36]
In Vim, I'm used to completing on nearby words using `Ctrl+N` and `Ctrl+P`.  It's much more likely that I would want to repeat the words that are around in the same file and especially around the cursor.
To get something similar, I think I would need the word list to prioritize words in the current file over words in other files.

Or, even easier to implement, allow me to enable the file scanner/provider but allow me to limit it to just the current file.

**Comment by tth05** [comment]
Basically like #19. Prioritization is also planned.

**Comment by huyz** [comment]
Ah I figured out what the type of completion is called: "Hippie completion"
https://www.jetbrains.com/go/guide/tips/cyclic-expand-word/
