### ISSUE TITLE
Navigation of auto-completion list with arrow keys not working since obsidian 1.0

### ISSUE THREAD

**Issue by nort4n** [tth05/obsidian-completr#40]
The arrow keys are assigned in the hotkeys settings but whenever I try to navigate the auto-completion list, the cursor jumps. The behavior is consistent on Win10 and MacOS versions of obsidian for me.

**Comment by tth05** [comment]
Should be fixed if you update to the newest version.

**Comment by nort4n** [comment]
Thanks, that did the trick.
