### ISSUE TITLE
German umlauts (äöüÄÖÜß) in Obsidian and coding of german.dic

### ISSUE THREAD

**Issue by merlinuwe** [tth05/obsidian-completr#41]
Thanks for your great plugin, which I currently have installed.

When I want to write for example "Vorwürfe", I get "Vorw�rfe" shown in the list and inserted in the text. Some UTF-8 issue, I guess. 

I use the german dictionary german.dic from https://sourceforge.net/projects/germandict/ I tried to open it in Notepad++. Regardless of the coding (ansi or utf-8) I see all german umlauts as they are (äöüÄÖÜß). I converted the file to utf-8, imported it again with your plugin but the problem remained the same in Obsidian.

When I activate "ignore diacritics when filtering" and try to write "Würfelaugen" (a word, which exists in the dictionary), I didn't get it in the list.

Then I went to P:\Obsidian\.obsidian\plugins\obsidian-completr\wordLists\german.dic and changed the existing file to my utf-8 coded file. And it works. ;-)

- Windows 10, latest with 16GB RAM
- Obsidian, latest 1.0.3
- Your plugin, latest
- .obsidian/plugins/obsidian-completr/wordLists/german.dic

Hope, that helps you to do something that makes it easier to use your plugin with german texts.

**Comment by tth05** [comment]
Looks like the `german.dic` file uses `windows-1252` encoding, which I didn't notice before. I added some code which tries to detect the encoding and then performs a conversion. This should work with this file at least. c00a4a6e7e90d93f6ec5168cd631da21d1c8df86
