### ISSUE TITLE
Profiles and plugins files

### ISSUE THREAD

**Issue by alabotski** [tth05/obsidian-completr#42]
Hi I use **.obsidian.desktop** as the main profile on my laptop

But [obsidian-completr](https://github.com/tth05/obsidian-completr)
Always save some filed in **.obsidian** folder
```
wordLists\
latex_commands.json
scanned_words.txt
```

**Comment by tth05** [comment]
Oh, I wasn't aware that the folder name can change. I'll look into it!

**Comment by tth05** [comment]
Fixed in 5e260163f42fdb71835831bcfc71778f8a62151a
