### ISSUE TITLE
Latex Autocomplete stop working after a certain document length

### ISSUE THREAD

**Issue by jensenraylight** [tth05/obsidian-completr#43]
by the way, i used completr for months now and really happy with the Latex Autocomplete.
i used it everyday, it boost my latex typing speed.

but today, the Latex autocomplete stop working,
when write latex, it didn't trigger any pop up.

i already tested it, 
i checked if there was anything that stop the autocomplete from triggering,
or if there was any loose "block" that prevent it.
but i don't think that was the problem.

and i think the Autocomplete stop working after 
either it hit a certain document length or if you use too many latex equation,
because, when i delete some equation, it start working again, but when it reach a
certain length, it stop working again.

i'm using obsidian v1.0, and i didn't auto update my obsidian and completr,
so, it's not something that was caused by update.

i didn't use any other autocomplete, only latex autocomplete

my workflow always required me to work in a long document, and use Header Outline to move around the document.
therefore, it'll be unecessary to cut the document everytime the autocomplete stop working.
so, i really wish the problem could be resolved

i include the gif in the attachment, 
it compared when i type at the bottom of the document vs the upper part of the document.

[completr bug.webm](https://user-images.githubusercontent.com/28711265/204594449-2a22a6c3-7702-4bb2-acf7-3e56fcc09b39.webm)

**Comment by tth05** [comment]
This issue comes from arbitrary limit of 1000 lines that I added, to save performance when checking for LaTeX blocks. I guess this was a bit too low. I'll fix it.

**Comment by jensenraylight** [comment]
Thanks for the response,
i didn't know about the limit, i thought my obsidian somehow acting up.

by the way, Thanks in Advance, 
the plugins really great, i really like it

**Comment by tth05** [comment]
2994ffef293ea1aa3291b477bca3c15e1b579abd
