### ISSUE TITLE
Allow for colons in autocomplete

### ISSUE THREAD

**Issue by dderom** [tth05/obsidian-completr#47]
Thanks for the plugin, works a charm. 

However, small feature request allowing for colons. 

User case: autocomplete for link types (using the Juggl plugin) in which I use (amongst others) the foaf link types. Aka, I use the foaf:document to highlight documents. 

The autocomplete halts when typing the ':'. Would it be an option to escape the colon character?

**Comment by tth05** [comment]
You could add the `:` to the word character regex in the settings. Does that solve your issue?
![image](https://user-images.githubusercontent.com/36999320/209719453-a8c551fc-e6ff-493b-a535-cc9b47636ad2.png)

**Comment by dderom** [comment]
That did it.

Thanks!

**Comment by bilke** [comment]
I have a similar problem: I would like to autocomplete user handles in the form `@username` so I simply added `@` to the character regex but unfortunately it does not work. Is there something else I need to consider?

Thanks!

**Comment by tth05** [comment]
> I have a similar problem: I would like to autocomplete user handles in the form `@username` so I simply added `@` to the character regex but unfortunately it does not work. Is there something else I need to consider?
> 
> Thanks!

Seems to work fine for me. Can you elaborate on what your character regex looks like and where you're completing?

**Comment by bilke** [comment]
Ah, I tried again today and now it works! My regex is this `a-zA-ZöäüÖÄÜß@:`. Thanks a lot for this plugin, it is really helpful!

**Comment by h4rsh-k** [comment]
@tth05 I want my autocomplete to only trigger with `:`. But only having `:` in the regex does not trigger autocomplete. I also tried `[\w:]+`. Any pointers please
