### ISSUE TITLE
Sequence syntax is not correctly recognized when there is spaces at the beginning of the line

### ISSUE THREAD

**Issue by Stardusten** [tth05/obsidian-completr#48]
Personally, I prefer to add two spaces at the beginning of the line when I use the sequence syntax. However this plugin doesn't seem to support this syntax.

Supported: 
```yaml
---
tags:
- a
- b
- c
---
```

Not Supported:

```yaml
---
tags:
   - a
   - b
   - c
---
```

Besides, if you define an array using sequence syntax with spaces, obsidian will allow you to fold this array.

![image](https://user-images.githubusercontent.com/38722307/211278719-b3d57ec6-a639-4ba8-a6a6-bba68e20274a.png)

![image](https://user-images.githubusercontent.com/38722307/211279028-9e1780dd-7b78-4574-a83d-efd3179850e5.png)

**Comment by tth05** [comment]
Fixed in 87468850762e1cf9e44b4a74a7f0188ffa640d83
