### ISSUE TITLE
Option to not select the first option in the dropdown by default

### ISSUE THREAD

**Issue by macintacos** [tth05/obsidian-completr#49]
I'm fine with the dropdown popping up - I just don't want any of those options to be selected until I arrow-down to them. The first option being pre-selected makes me run into the following issues (which are unfortunately making me have to disable this plugin since it's so disruptive):

- When I hit "enter" and the completion menu is showing, it accepts that option, even though sometimes I feel like I'm already "done" writing the word and just want to insert a literal line break. When this happens, I have to undo, hit "escape" to make sure the dropdown isn't shown, and _then_ hit "enter" to insert the linebreak.
- I use vim-mode. When in insert mode, I will often be in the middle of typing a word and want jump back to normal mode to do some other operation, however, if the completion menu is up, the first time I hit "escape" it is registered by Obsidian as dismissing the dropdown, and leaves me in insert mode. This often leads me to getting into a habit of pressing "escape" several times just because I want to "be sure" that I'm in normal mode, and when I forget it leads me to entering text where I wish I wasn't.

I think that all of this would probably be resolved if the "focus" was not given to the completion options until the user presses the down arrow (or something like that) to intentionally go into the completion menu to choose an option.

Hopefully that makes sense! Please let me know if you need me to clarify anything.

**Comment by tth05** [comment]
Definitely a good idea. I think an option to disable auto-trigger would be helpful as well.

**Comment by tth05** [comment]
Added in af18c9a9af427a6eb880717753eb7f0b184c7471.
I actually like this behavior a lot. Nice suggestion!
