### ISSUE TITLE
It seems doesn't work with Chinese characters

### ISSUE THREAD

**Issue by huanlin** [tth05/obsidian-completr#52]
It works well with English characters, but not Chinese.
Hopefully Chinese characters can be supported.

**Comment by tth05** [comment]
Did you modify the character regex in the settings? Something like `\p{Han}` should include all chinese characters.

**Comment by tth05** [comment]
@huanlin Did that help?

**Comment by SourignaSimmalavong** [comment]
In case it can help someone else, it works if you use `\p{sc=Han}` (https://javascript.info/regexp-unicode)
