### ISSUE TITLE
[Feature request] Import dictionary into blacklist

### ISSUE THREAD

**Issue by lebigot** [tth05/obsidian-completr#56]
I type fast enough that the (text, not LaTeX, etc.) suggestions are useless to me. Now, what would be useful in this situation is if Completr suggested words _that are not in the dictionary_ (but, in the document or vault, as usual): this would be very useful for proper names, brand names, company names, etc.

**Comment by tth05** [comment]
You should be able to achieve this if you instead paste your dictionary into the `blacklisted_suggestions.txt` file inside of the plugins folder.
In the future, importing a dictionary as a blacklist might definitely be useful.

**Comment by lebigot** [comment]
Thanks for the tip.

Now, I found another way to achieve the desired result (no constant popup): I simply removed the automatic popup and call the list of suggestions it as needed.

**Comment by tth05** [comment]
> Thanks for the tip.
> 
> Now, I found another way to achieve the desired result (no constant popup): I simply removed the automatic popup and call the list of suggestions it as needed.

Sound like just disabling auto-trigger

**Comment by lebigot** [comment]
Indeed.
