### ISSUE TITLE
Consider keeping word file order

### ISSUE THREAD

**Issue by xmacex** [tth05/obsidian-completr#58]
Thanks for a very interesting plugin. While I realize it becomes non-trivial if one has multiple word files, I wonder if it would make sense to keep the order of the word files? This way empirical, corpus-linguistic information e.g. from [the word lists linked on the frontpage](https://github.com/tth05/obsidian-completr#looking-for-word-lists) could inform suggestions and enhance the experience. I assumed keeping the order would be the case, but it isn't (or I am confused, which is of course very likely).

For example comparing the completions for `philosoph` and a single word file, I am not sure if I understand what the order is.

# FrequencyDictionaries

From https://github.com/kpym/FrequencyDictionaries

<img width="1283" alt="frequencyDictionaries" src="https://user-images.githubusercontent.com/879300/227775997-a801fba4-1e65-4079-899d-6a9aeadcac8a.png">

```sh
╰─ grep -n "^philosoph" large_en.txt
2741:philosophy
7040:philosophical
8703:philosopher
10607:philosophers
20110:philosophies
35770:philosophically
45020:philosophie
46609:philosopher's
50497:philosophic
97027:philosophizing
109134:philosophia
111650:philosophize
115705:philosophique
118553:philosophes
122827:philosophe
122828:philosophiae
143110:philosophische
159496:philosophiques
163432:philosophising
165431:philosophy's
167383:philosophica
177739:philosophicus
179933:philosophorum
208578:philosoph
216331:philosophise
235746:philosophischen
235747:philosophus
263293:philosophisch
```

The information about order is lost.

# Using the standard unix `words` file

<img width="1283" alt="standard words" src="https://user-images.githubusercontent.com/879300/227776014-025c1ac9-98df-4c2c-ae06-eb1921d95642.png">

And grepping the word file in `/usr/share/dict/words` on macOS

```sh
╰─ grep -n "^philosoph" /usr/share/dict/words
144755:philosoph
144756:philosophaster
144757:philosophastering
144758:philosophastry
144759:philosophedom
144760:philosopheme
144761:philosopher
144762:philosopheress
144763:philosophership
144764:philosophic
144765:philosophical
144766:philosophically
144767:philosophicalness
144768:philosophicide
144769:philosophicohistorical
144770:philosophicojuristic
144771:philosophicolegal
144772:philosophicoreligious
144773:philosophicotheological
144774:philosophism
144775:philosophist
144776:philosophister
144777:philosophistic
144778:philosophistical
144779:philosophization
144780:philosophize
144781:philosophizer
144782:philosophling
144783:philosophobia
144784:philosophocracy
144785:philosophuncule
144786:philosophunculist
144787:philosophy
```

I hope this is helpful or interesting, and in any case I am grateful for the 📖 plugin. Well done!

**Comment by tth05** [comment]
The ranking is currently just based on word length and whether or not case matches. I'd definitely like to redo the ranking overall. Something like the order in which the words appear in the loaded file could be a contributing factor. I'll keep it in mind.
