### ISSUE TITLE
Options to limit suggestions in certain contexts

### ISSUE THREAD

**Issue by Tohsig** [tth05/obsidian-completr#6]
Last week I threw together [a plugin](https://github.com/Tohsig/obsidian-front-matter-tag-wizard) to suggest and format front matter tags, but when I submitted for review I was pointed in the direction of your awesome plugin! 

What I'm interested in is an option to limit `tags:` suggestions to just tags that have been defined elsewhere in the vault. So instead of a full word list, you would just get the words that you're explicitly using as tags. 

Ditto for `key:` suggestions. Would love to be able to just have other words that I've used as front matter keys suggested rather than a full word list.

Would you be interested in adding, or accepting PRs for, either option?

**Comment by tth05** [comment]
It should already only suggest existing tags, if there exists at least one tag in the vault. If that's working for you, I'd count it as a bug :D

**Comment by Tohsig** [comment]
Ha! I think I see what happened, and it's 100% user error. I've been abusing the fact that Obsidian recognizes front matter tags even if they're not in a proper array. So all of my vault tags are written as `tags: word1, word2` instead of `tags: [word1, word2]`. I'm guessing your parser is correctly assuming valid YAML. Without the closing `]`, I assume the parser is recognizing every word in each note as a potential tag. Testing a fresh vault with a handful of notes seems to prove the theory. 

So, I have a follow up question. I see that typing `publish:` will auto-suggest `true | false`. Should that same behavior be happening with other front matter keys? 

For example, if I have a note with `status: pending` and another with `status: complete`, would a third note immediately suggest `pending | complete` after I type `status:`?

**Comment by tth05** [comment]
I've noticed some issues regarding the new minimum word length option I added. Made some fixes. 

> For example, if I have a note with status: pending and another with status: complete, would a third note immediately suggest pending | complete after I type status:?

This should work now.

> Ditto for key: suggestions. Would love to be able to just have other words that I've used as front matter keys suggested rather than a full word list.

This should work now.

> Ha! I think I see what happened, and it's 100% user error. I've been abusing the fact that Obsidian recognizes front matter tags even if they're not in a proper array. So all of my vault tags are written as tags: word1, word2 instead of tags: [word1, word2]. I'm guessing your parser is correctly assuming valid YAML. Without the closing ], I assume the parser is recognizing every word in each note as a potential tag. Testing a fresh vault with a handful of notes seems to prove the theory.

That's indeed correct. I use what obsidian gives me, but it seems like they don't convert `tag1, tag2` into an array, which breaks my code.

**Comment by tth05** [comment]
> I wonder if there's a way to trigger the suggestion pop-up immediately after selecting a previous suggestion. So to use my previous example, I'd select the suggestion for status: # and it would immediately bring up a suggestion pop-up with pending | complete. I think it would have to be a hacky approach, because Obsidian doesn't call onTrigger after a text replacement and I don't think there's a way to do it manually.

Yeah this would probably require a hacky solution. Always open for PRs :)

> On the tags thing, check out Obsidian's getAllTags if you haven't already. That's what I [did here](https://github.com/Tohsig/obsidian-front-matter-tag-wizard/blob/master/src/extractTagsFromFileCaches.ts?rgh-link-date=2022-02-15T13%3A50%3A58Z), based on the approach Dataview uses.

Thanks, didn't know about that function. I've switched to using it here 5ff0118562ec7ee987e37f171491477089b09742

> Last note, a minor quality of life improvement would be to only suggest tags within the [ ] brackets. This only comes into play if I'm deleting the line after tags: and my cursor ends up next to the ].

I've changed it so the popup won't get triggered when switching to the previous line for now. It's not perfect, but less annoying :D d0082176ba39d6560678f66aadbd26f9e1a1a04e

**Comment by tth05** [comment]
I think this could be closed for now?

**Comment by Tohsig** [comment]
Great stuff! Yup, you've definitely more than addressed everything here. Thanks!
