### ISSUE TITLE
VietNamese word is not working well

### ISSUE THREAD

**Issue by LeVietHa05** [tth05/obsidian-completr#61]
I have words like: 
- ăn
- uống
- phở
- bong
- chanh
- phang
- ....
This plugin works well with word like: bang, chanh, or phang, but the suggestion popup does not show up when I try writing words like: "ăn", "uống", ...

**Comment by tth05** [comment]
You need to modify the character regex in the options. See https://github.com/tth05/obsidian-completr/issues/52
Adding `\p{L}` would include any letter from any language. `\p{sc=Latin}` might be more specific. You can read more here https://www.regular-expressions.info/unicode.html
