### ISSUE TITLE
Mobile/Android Support

### ISSUE THREAD

**Issue by MaxWolf-01** [tth05/obsidian-completr#64]
I get "This plugin does not support your device" on Obsidian Mobile.

Could mobile be supported?

OS: Android 12 aarch64

**Comment by tth05** [comment]
Supporting multiple platforms is probably not that hard, but going through the extra testing is not worth the time for me on a platform I don't even use.

See also https://github.com/tth05/obsidian-completr/issues/51.
Maybe editing the manifest file works now?

**Comment by mathisgauthey** [comment]
> Supporting multiple platforms is probably not that hard, but going through the extra testing is not worth the time for me on a platform I don't even use.
> 
> See also https://github.com/tth05/obsidian-completr/issues/51.
> Maybe editing the manifest file works now?

Just wanted to share that the manifest editing worked on my end using Android on a Google pixel 7.

I use this plugin only for the callout auto-completion feature with obsidian-callout-manager and it works on Android as well ! 👍

**Comment by shui-dun** [comment]
Can run normally on Android, tested simply.
