### ISSUE TITLE
[enhancement]Don't trigger newline on tag auto-complete

### ISSUE THREAD

**Issue by Smitty010** [tth05/obsidian-completr#66]
I have tags in my frontmatter that look like
```
tags:
- tag1
- tag2
```
Sometimes I just want to change a tag name.  It's a bit annoying that when I hit return to accept the new word, it not only accepts the new word, but it also creates a place for a new tag (which I don't really want).  For example, if I try to change tag2 above to tag 3, I end up with:

```
tags:
- tag1
- tag3
- 
```

It would be nice if it didn't put the next hyphen after

**Comment by tth05** [comment]
There should be an option for this in the settings

**Comment by Smitty010** [comment]
I missed it the first time.  "Add suffix to tag completion".  The title doesn't match the description for me.  But, I've turned it off.  Thanks
