### ISSUE TITLE
LaTeX completion will be triggered after the certain line number

### ISSUE THREAD

**Issue by zcysxy** [tth05/obsidian-completr#7]
Thanks for this fantastic plugin; the LaTeX auto-completion is the killer feature to me. If I'm not mistaken, the correct logic is that LaTeX completion is only triggered in the math environment, i.e., between dollar signs. However, I found that the LaTeX completion will be triggered after the certain line number: 50 on my end. Here's a git demonstrates it

![demo](https://user-images.githubusercontent.com/48207708/153710484-8af1cd0f-7634-4262-a9f6-084f8a52b12a.gif)

Please let me know if this is a bug or the intended behavior.

**Comment by tth05** [comment]
Well, this was something I want to prevent by writing a new LaTeX block scanner, but then still wrote it in a way where this happens ...
Fixed in df029ed78edd6ce1ffeaeeb71d497fed3e8da5fa
