### ISSUE TITLE
Use \p{...} in Word Character Regex option

### ISSUE THREAD

**Issue by tempapy** [tth05/obsidian-completr#8]
Hello,
First, thank you for you plugin, I can stop using Visual Studio Code for writing notes now 😄 !

The only thing is that there are a lot a diacritics in my words (such as é, ū, ṛ etc.) so I don't really want to type every single one of them in the Word Character Regex option.

But the problem is, the regex expression \p{...} doesn't seem to work here: I tried \p{L} and \p{Latin}, which should select all unicode latin letters, but it doesn't work.

Thank you for your help

**Comment by tth05** [comment]
I'm sorry. Unicode mode wasn't enabled for the character regex. You should now be able to use `\p{L}` or `\p{Script=Latin}` :)

Fix 34f2e3a0b2f622580b6609323a6b5f9658bbe523
