### ISSUE TITLE
Use Tab instead of enter to insert suggestion 

### ISSUE THREAD

**Issue by JoshKasap** [tth05/obsidian-completr#9]
Could you make an option to change the insert key to be tab instead of enter?

**Comment by tth05** [comment]
Implemented in 3445cdc00680661fb8e1fd9ba190b88d2c694499

**Comment by tth05** [comment]
I just noticed you said `instead of`. The change I made allows you to use both. Is that fine?

**Comment by JoshKasap** [comment]
For my use case, I definitely want instead of not both. But if you can make it an option to make it enter, tab, or both. That would be ideal. I'm sure some people would like both. 

Enter doesn't work for me because I often hit enter to go to the next line and with enter being the activation key it often causes issues where I need to hit enter twice to go to the next line which I don't like. This is especially noticeable when working with bullet points. It also increases the risk of accidentally autocompleting a word I didn't want to. 

Tab on the other hand is almost exclusively used to indent lines which generally happens before typing any text so it's unlikely I'll never run into an issue of typing a word and then immediately hitting tab.

**Comment by tth05** [comment]
For the bullet list reason I've implemented the ability to hold shift to bypass the popup and perform a normal enter press.

**Comment by JoshKasap** [comment]
BTW I just noticed the tab implementation you added doesn't allow you to un-tab bullet points, headers, etc. with the traditional `shift + tab`. This is the case even if you are on a blank line and the auto complete box isn't open.

**Comment by tth05** [comment]
Yeah I just went to quick about implementing this. I'm going to redo it anyway.

**Comment by tth05** [comment]
I've implemented it as a switch now. 8005b850a1957cedd451a6fd2b75704f22062c5d

**Comment by paw-lu** [comment]
Just checking here @tth05, do we have the option to use <kbd>tab</kbd> at all right now as the insertion key without the workaround? Or does it require the workaround even if we're okay with it sharing the action with <kbd>return</kbd>?

<kbd>tab</kbd> doesn't seem to be working for me right now, and I don't see a way to switch it to <kbd>tab</kbd> in settings.

**Comment by tth05** [comment]
> Just checking here @tth05, do we have the option to use tab at all right now as the insertion key without the workaround? Or does it require the workaround even if we're okay with it sharing the action with return?
> 
> tab doesn't seem to be working for me right now, and I don't see a way to switch it to tab in settings.

Do you mean you can change it to `Tab` but it doesn't work, or just that you can't change it? As pointed to in the README, the second issue is a problem with Obsidian. The workaround takes less than a minute, so I don't see the problem with using that for now.

**Comment by paw-lu** [comment]
I worded this badly @tth05 😅.

I was trying to ask if <kbd>tab</kbd> was meant to work by default. But I looked at the implimentation and it seems like it wasn't. The workaround you linked worked perfectly for remapping to <kbd>tab</kbd>.

Thanks!
