### ISSUE TITLE
Tab to autocomplete?

### ISSUE THREAD

**Issue by wazeerc** [tth05/obsidian-completr#90]
Is there a way to trigger an autocomplete by using "Tab" instead of "Enter"?

**Comment by linuswalter** [comment]
Yes. It doesn't work via the official Obsidain Hotkey window, but you can open the `.obsidian/hotkeys.json` file and search for the line
```json
  "obsidian-completr:completr-insert-selected-suggestion": [
    {
      "modifiers": [],
      "key": "Enter"
    }
  ],
```
And just insert `Tab` instead of `Enter`. For me it worked

**Comment by wazeerc** [comment]
Thanks @linuswalter !
